# Generated by Django 5.2.1 on 2025-05-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='member',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='trainer',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_block',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
