# Generated by Django 5.2.1 on 2025-05-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0002_alter_schedule_options_remove_schedule_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Thứ hai'), (1, 'Thứ ba'), (2, 'Thứ tư'), (3, 'Thứ năm'), (4, 'Thứ sáu'), (5, 'Thứ bảy'), (6, 'Chủ nhật')]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_block',
            field=models.CharField(choices=[('1_morning', 'Sáng'), ('2_afternoon', 'Trưa'), ('3_evening', 'Chiều')], max_length=12),
        ),
    ]
