# Generated by Django 5.2.1 on 2025-05-24 19:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0002_remove_userprofile_avatar_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1748023865/default_uryokl.png', max_length=255, verbose_name='avatar'),
        ),
    ]
