# Generated by Django 5.2.1 on 2025-05-21 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0003_alter_schedule_day_of_week_alter_schedule_time_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pes.schedule'),
        ),
    ]
