# Generated by Django 5.2.1 on 2025-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0004_alter_class_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
