# Generated by Django 5.2.1 on 2025-05-22 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0005_alter_membership_end_date_alter_trainer_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='schedule',
        ),
        migrations.AddField(
            model_name='class',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pes.class')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pes.schedule')),
            ],
        ),
    ]
