# Generated by Django 5.2.1 on 2025-05-25 16:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='image/upload/v1748190880/default_lccdvq.png', max_length=255, verbose_name='avatar'),
        ),
    ]
