# Generated by Django 5.2.1 on 2025-05-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0006_remove_class_schedule_class_price_classschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pes.class'),
        ),
    ]
