# Generated by Django 5.2.1 on 2025-05-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0008_alter_classschedule_lop_alter_classschedule_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='lop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pes.class'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pes.schedule'),
        ),
    ]
