# Generated by Django 5.2.1 on 2025-05-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pes', '0009_alter_classschedule_lop_alter_classschedule_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='pes.trainer'),
        ),
    ]
